### ISSUE TITLE
已失效

### ISSUE THREAD

**Issue by wjm** [cheny95/rrmj-for-chrome#1]
能搜索没有视频链接

**Comment by cheny95** [comment]
已经修复。

**Comment by wjm** [comment]
现在发现chrome不会播放而是自动下载了怎么办= =

**Comment by cheny95** [comment]
@wjm2038  这就是浏览器的问题了，它识别到了地址直接下载了。

现在这个版本针对较新的视频是可以播放的，老视频还有点问题。想修复可以观看吧，有时间再兼容下老视频。

**Comment by wjm** [comment]
嗯，这个应该能改成调用vlc播放之类的吧，我自己尝试搞一搞

**Comment by cheny95** [comment]
好的，辛苦你了。

**Comment by wjm** [comment]
也得先谢谢您写的插件。 还想请教下这个接口是哪里获取的呢？

**Comment by cheny95** [comment]
你可以看main.js，接口请求都在里面，获取接口的方式是抓包。本来想写着自己用的，顺带发到github上的，工作太忙没时间看视频，就没注意到需要维护，代码比较糙，将就看一下。
