### ISSUE TITLE
现在需要key来调用

### ISSUE THREAD

**Issue by wjm** [cheny95/rrmj-for-chrome#2]
http://ks3-cn-beijing.ksyun.com/rrtv-test/pochanjmS2/pocjmS2E19.rmvb
`<Error>`
`<Code>NoSuchKey</Code>`
`<Message>The specified key does not exist.</Message>`
`<Resource>/rrtv-test/pochanjmS2/pocjmS2E19.rmvb</Resource>`
`<RequestId>bdd133c9009842bb89ed6b3ec65131a2</RequestId>`
`</Error>`

**Comment by cheny95** [comment]
因为人人美剧现在的API也都是聚合网上其他的资源了，很乱，无法一一匹配成功。
暂时不维护了，等稳定或者找到更好的源。
